services:

  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: agriculture_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agriculture-network

  redis:
    image: redis:8
    container_name: redis-container
    networks:
      - agriculture-network

  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - agriculture-network

volumes:
  postgres_data:

networks:
  agriculture-network: