name: Smart Agriculture CI/CD

on:
  push:
    branches:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
     

            echo "Starting deployment..."

            sudo docker pull leadsamit/smart-agriculture-backend:v1

            echo "Creating Docker network..."
            sudo docker network create agriculture-network || true

            echo "Stopping old backend..."
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true

            echo "Connecting PostgreSQL to network..."
            sudo docker network connect agriculture-network postgres-container || true

            echo "Connecting Redis to network..."
            sudo docker network connect agriculture-network redis-container || true

            echo "Starting backend..."

            sudo docker run -d \
              --name backend-container \
              --restart unless-stopped
              --network agriculture-network \
              -p 8000:8000 \
              leadsamit/smart-agriculture-backend:v1

            echo "Waiting for backend..."
            sleep 10

            echo "Backend status:"
            sudo docker ps

            echo "Testing backend..."
            sudo docker exec backend-container \
              python -c "import urllib.request; print(urllib.request.urlopen('http://localhost:8000/').read().decode())"

            echo "Deployment completed successfully!"